   name: Run Tests

   on:
     push:
       branches:
         - main

   jobs:
     test:
       runs-on: ubuntu-latest

       steps:
         - uses: actions/checkout@v2

         - name: Set up JDK 11
           uses: actions/setup-java@v2
           with:
             java-version: '11'

         - name: Build with Maven
           run: mvn clean test

         - name: Upload Allure results
           uses: actions/upload-artifact@v2
           with:
             name: allure-results
             path: target/allure-results
